In [1]:
i=1
n=3

In [2]:
while(i<=10):
    print(n, "*", i, "=", n*i)
    i=i+1

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30


In [3]:
l1 = ["blue","green","red"]


In [4]:
print(l1)

['blue', 'green', 'red']


In [5]:
for "blue" in range()

SyntaxError: cannot assign to literal (375073674.py, line 1)

In [8]:
for i in l1:
    print(i)

blue
green
red


In [9]:
color = ["red","blue","pink"]
item = ["phone","chair","book"]

In [10]:
for i in color:
    for j in item:
        print(i,j)

red phone
red chair
red book
blue phone
blue chair
blue book
pink phone
pink chair
pink book


In [12]:
def odd_even(x):
    if x%2==0:
        print(x, "is even")
    else:
        print(x, "is odd")

In [13]:
odd_even(5)

5 is odd


In [14]:
odd_even(4)

4 is even


In [15]:
def add(x):
    return(x+100)

In [16]:
add(50)

150

In [17]:
marks= [50,60,98,54,99,100,45,87,65]

In [22]:
for i in marks:
    if i== 100:
        print(i)
        i=i+1

100


In [23]:
for i in marks:
    if i== 100:
        print(i)
        i=i+1

100


In [24]:
for i in marks:
    print(i)

50
60
98
54
99
100
45
87
65


In [25]:
 import numpy as np

In [26]:
n1=np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [28]:
 n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [35]:
n1=np.zeros((6,6))
n1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
n1= np.full((3,3),7)
n1

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [38]:
import pandas as pd
s1= pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64